# These are supported funding model platforms

# GitHub Sponsors
github: [ReferConnect]

# Open Collective
# open_collective: referconnect

# Patreon
# patreon: referconnect

# Ko-fi
ko_fi: I3I31MM8N2

# Buy Me a Coffee
# buy_me_a_coffee: referconnect

# Custom URLs (up to 4)
# custom: ['https://referconnect.com/donate', 'https://paypal.me/referconnect']
